<?php
/**
 * Plugin Name: Syndication Links
 * Plugin URI: http://wordpress.org/plugins/syndication-links
 * Description: Add Syndication Links to Your Content
 * Version: 4.0.0
 * Author: David Shanske
 * Author URI: http://david.shanske.com
 * Text Domain: syndication-links
 * Domain Path:  /languages
 */

define( 'SYNDICATION_LINKS_VERSION', '4.0.0' );

// Icon Information
require_once plugin_dir_path( __FILE__ ) . '/includes/simple-icons.php';

// Information on Metadata
require_once plugin_dir_path( __FILE__ ) . '/includes/class-syn-meta.php';

// Configuration Options
require_once plugin_dir_path( __FILE__ ) . '/includes/class-syn-config.php';
new Syn_Config();

// Social Plugin Add-Ons
require_once plugin_dir_path( __FILE__ ) . '/includes/class-social-plugins.php';

// Syndication Providers
require_once plugin_dir_path( __FILE__ ) . '/includes/class-syndication-provider.php';
require_once plugin_dir_path( __FILE__ ) . '/includes/class-syndication-provider-indienews.php';

add_filter( 'syn_syndication_targets', 'syn_add_targets' );

function syn_add_targets( $targets ) {
	$targets[] = new Syndication_Provider_Indienews();
	return $targets;
}


// Global Functions
require_once plugin_dir_path( __FILE__ ) . '/includes/functions.php';

// Post Syndication Logic
require_once plugin_dir_path( __FILE__ ) . '/includes/class-post-syndication.php';
new Post_Syndication();

function syndication_links_load_plugin_textdomain() {
	load_plugin_textdomain( 'syndication-links', false, basename( dirname( __FILE__ ) ) . '/languages/' );
}
add_action( 'plugins_loaded', 'syndication_links_load_plugin_textdomain' );

function syndication_links_privacy_declaration() {
	if ( function_exists( 'wp_add_privacy_policy_content' ) ) {
		$content = __(
			'Syndication Links, which are links to the same content on other sites, may be displayed on comments, but only if supplied by the submitter or if your comment was
			generated by webmention, if they appear on your site.', 'syndication-links'
		);
		 wp_add_privacy_policy_content(
			 'Syndication Links',
			 wp_kses_post( wpautop( $content, false ) )
		 );
	}
}

add_action( 'admin_init', 'syndication_links_privacy_declaration' );
